### ISSUE TITLE
Trying to run the importer on WP4.5.2, jquery error

### ISSUE THREAD

**Issue by presswizards** [humanmade/WordPress-Importer#52] opened 2016-05-11 05:15 UTC
Red Error in the Chrome console:
import.js:24

Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.

Line 24 is:

document.getElementById( 'progressbar-' + type ).value = percent * 100;

I just hard-coded it to 100 and then it continued without error, please fix?

This plugin worked great with partial posts only export and brought over the images properly too, which is exactly what I was hoping to use it for.

**Comment by swissspidy** [comment] 2016-05-23 16:53
Looks like a duplicate of #40.

**Closed by swissspidy** 2016-05-23 16:53 UTC
Labels: Bug
